#!/usr/bin/env python3
"""
Generate presentation markdown from course materials.

This script takes the outline, brief, and research notes and generates
a formatted markdown presentation ready for delivery.

Usage:
    python generate_presentation.py \
        --outline course_outline.json \
        --brief content_brief.json \
        --research research_notes.json \
        --template templates/presentation_template.md \
        --output final_presentation.md
"""

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any


class PresentationGenerator:
    """Generate markdown presentation from course materials."""

    def __init__(
        self,
        outline_path: str,
        brief_path: str,
        research_path: str,
        template_path: str = None
    ):
        self.outline_path = Path(outline_path)
        self.brief_path = Path(brief_path)
        self.research_path = Path(research_path)
        self.template_path = Path(template_path) if template_path else None

        self.outline = None
        self.brief = None
        self.research = None

        self.slides = []

    def load_files(self):
        """Load all input files."""
        print("Loading input files...")

        # Load outline
        with open(self.outline_path, 'r', encoding='utf-8') as f:
            self.outline = json.load(f)
        print(f"  ✓ Loaded outline: {self.outline_path}")

        # Load brief
        with open(self.brief_path, 'r', encoding='utf-8') as f:
            self.brief = json.load(f)
        print(f"  ✓ Loaded brief: {self.brief_path}")

        # Load research
        with open(self.research_path, 'r', encoding='utf-8') as f:
            self.research = json.load(f)
        print(f"  ✓ Loaded research: {self.research_path}")

    def generate(self) -> str:
        """Generate complete presentation markdown."""
        print("\nGenerating presentation...")

        self.load_files()

        # Build slides
        self._add_front_matter()
        self._add_title_slide()
        self._add_course_overview()
        self._add_learning_objectives()
        self._add_prerequisites()
        self._add_course_structure()

        # Generate module content
        for module in self.brief.get('modules', []):
            self._add_module_content(module)

        # Add conclusion
        self._add_course_conclusion()
        self._add_references()

        # Combine into single document
        presentation = '\n\n'.join(self.slides)

        print(f"✓ Generated presentation with {len(self.slides)} slide sections")

        return presentation

    def _add_front_matter(self):
        """Add YAML front matter."""
        metadata = self.outline.get('course_metadata', {})

        front_matter = f"""---
title: {metadata.get('title', 'Course Title')}
author: Generated by Course Presentation Builder
date: {datetime.now().strftime('%Y-%m-%d')}
---"""

        self.slides.append(front_matter)

    def _add_title_slide(self):
        """Generate title slide."""
        metadata = self.outline.get('course_metadata', {})

        slide = f"""# {metadata.get('title', 'Course Title')}

**{metadata.get('subtitle', '')}**

Generated: {datetime.now().strftime('%B %d, %Y')}

<!--
SPEAKER NOTES:
- Welcome participants
- Brief introduction
- Set expectations for the course
-->"""

        self.slides.append(slide)

    def _add_course_overview(self):
        """Generate course overview slide."""
        metadata = self.outline.get('course_metadata', {})
        modules = self.outline.get('modules', [])

        # Extract main topic areas from modules
        topic_areas = [m.get('module_title', f"Module {m.get('module_number')}")
                      for m in modules[:3]]  # Show first 3

        slide = f"""---

## Course Overview

**What This Course Covers:**

{self._format_bullets(topic_areas)}

**Target Audience:**

{metadata.get('target_audience', 'Not specified')}

**Duration:** {metadata.get('duration', 'Not specified')}

<!--
SPEAKER NOTES:
- Explain course scope and boundaries
- Ask participants to introduce themselves briefly
- Estimated time: 10 minutes
-->"""

        self.slides.append(slide)

    def _add_learning_objectives(self):
        """Generate learning objectives slide."""
        objectives = self.outline.get('course_objectives', [])

        if not objectives:
            # Extract from first few sections if not at course level
            objectives = []
            for module in self.outline.get('modules', [])[:2]:
                for section in module.get('sections', [])[:2]:
                    objectives.extend(section.get('learning_objectives', []))
                    if len(objectives) >= 5:
                        break
                if len(objectives) >= 5:
                    break

        slide = f"""---

## Learning Objectives

By the end of this course, you will be able to:

{self._format_numbered_list(objectives[:5])}

<!--
Use these objectives to guide your learning and assess your progress.
-->"""

        self.slides.append(slide)

    def _add_prerequisites(self):
        """Generate prerequisites slide."""
        metadata = self.outline.get('course_metadata', {})
        prereqs = metadata.get('prerequisites', [])

        if not prereqs:
            # Skip if no prerequisites
            return

        slide = f"""---

## Prerequisites

**Required Knowledge:**

{self._format_bullets(prereqs)}

<!--
SPEAKER NOTES:
- Quick poll: Who has experience with prerequisites?
- Address any gaps with supplementary resources
- Set realistic expectations based on background
-->"""

        self.slides.append(slide)

    def _add_course_structure(self):
        """Generate course structure overview slide."""
        modules = self.outline.get('modules', [])

        module_list = []
        for module in modules:
            mod_num = module.get('module_number', '?')
            mod_title = module.get('module_title', 'Untitled')
            mod_hours = module.get('estimated_hours', 0)
            module_list.append(f"**Module {mod_num}:** {mod_title} ({mod_hours}h)")

        slide = f"""---

## Course Structure

{self._format_lines(module_list)}

<!--
SPEAKER NOTES:
- Show the learning journey
- Explain how modules build on each other
- Preview assessments and milestones
-->"""

        self.slides.append(slide)

    def _add_module_content(self, module: Dict):
        """Generate content for a complete module."""
        mod_num = module.get('module_number', '?')
        mod_title = module.get('module_title', 'Untitled Module')
        mod_desc = module.get('module_description', '')

        # Get module objectives from outline
        outline_module = self._find_outline_module(mod_num)
        mod_objectives = outline_module.get('module_objectives', []) if outline_module else []

        # Module introduction
        slide = f"""---

# Module {mod_num}: {mod_title}

**Overview:** {mod_desc}

**Learning Goals:**

{self._format_bullets(mod_objectives[:3])}

<!--
SPEAKER NOTES:
- Introduce module context and importance
- Connect to course objectives
- Preview section sequence
- Estimated time: 5 minutes
-->"""

        self.slides.append(slide)

        # Module roadmap
        sections = module.get('sections', [])
        section_list = [
            f"{sec.get('section_number')}. {sec.get('section_title', 'Untitled')}"
            for sec in sections
        ]

        roadmap_slide = f"""---

## Module {mod_num} Roadmap

**We'll cover:**

{self._format_numbered_list(section_list)}

**By the end, you'll be able to:**

{self._format_bullets(mod_objectives[:2] if mod_objectives else ["Complete module learning goals"])}"""

        self.slides.append(roadmap_slide)

        # Generate each section
        for section in sections:
            self._add_section_content(mod_num, section)

        # Module summary
        self._add_module_summary(mod_num, mod_title, sections)

    def _add_section_content(self, mod_num: int, section: Dict):
        """Generate content for a section."""
        sec_num = section.get('section_number', '?')
        sec_title = section.get('section_title', 'Untitled Section')
        learning_objs = section.get('learning_objectives', [])

        # Section introduction
        slide = f"""---

## {mod_num}.{sec_num} {sec_title}

**Learning Objectives:**

{self._format_bullets(learning_objs)}

<!--
SPEAKER NOTES:
- Estimated time for section: [X minutes]
- Open with motivating question or scenario
- Set expectations for what we'll accomplish
-->"""

        self.slides.append(slide)

        # Add core content
        core_content = section.get('core_content', {})
        self._add_core_content_slides(mod_num, sec_num, sec_title, core_content)

        # Add examples
        examples = section.get('examples_and_applications', {})
        self._add_example_slides(mod_num, sec_num, examples)

        # Add research findings
        self._add_research_slides(mod_num, sec_num)

        # Section summary
        self._add_section_summary(mod_num, sec_num, sec_title, learning_objs)

    def _add_core_content_slides(
        self,
        mod_num: int,
        sec_num: int,
        sec_title: str,
        core_content: Dict
    ):
        """Generate slides for core content."""
        key_points = core_content.get('key_points', [])
        concepts = core_content.get('concepts_to_explain', [])
        definitions = core_content.get('definitions', {})

        # Key points slide
        if key_points:
            slide = f"""---

### Key Concepts: {sec_title}

{self._format_bullets(key_points[:6])}

<!--
SPEAKER NOTES:
- Emphasize connections between concepts
- Use examples to illustrate each point
-->"""
            self.slides.append(slide)

        # Concept explanation slides
        for concept in concepts[:2]:  # Limit to avoid too many slides
            if isinstance(concept, dict):
                concept_name = concept.get('concept', 'Concept')
                explanation = concept.get('current_understanding', '')
                approach = concept.get('explanation_approach', '')

                slide = f"""---

### {concept_name}

**Definition:**

{explanation or 'Core concept to be explained'}

**Teaching Approach:**

{approach or 'Step-by-step explanation with examples'}

<!--
SPEAKER NOTES:
- Start with concrete before abstract
- Check for understanding before moving on
-->"""
                self.slides.append(slide)

        # Definitions slide (if any important ones)
        if definitions and len(definitions) <= 5:
            def_items = [f"**{term}**: {defn}" for term, defn in list(definitions.items())[:5]]

            slide = f"""---

### Key Terminology

{self._format_lines(def_items)}

<!--
SPEAKER NOTES:
- Ensure everyone understands key terms
- Provide examples of usage
-->"""
            self.slides.append(slide)

    def _add_example_slides(self, mod_num: int, sec_num: int, examples: Dict):
        """Generate slides for examples."""
        video_examples = examples.get('from_video', [])

        for example in video_examples[:1]:  # Show at most 1 video example per section
            if isinstance(example, dict):
                ex_title = example.get('example', 'Example')
                timestamp = example.get('timestamp', '')
                topics = example.get('topics_illustrated', [])

                slide = f"""---

### Example: {ex_title}

{example.get('example', 'Example description')}

**Illustrates:**

{self._format_bullets(topics)}

<!--
SPEAKER NOTES:
- Source: Video at {timestamp}
- Engage with: "What would you do in this situation?"
-->"""
                self.slides.append(slide)

    def _add_research_slides(self, mod_num: int, sec_num: int):
        """Add slides with research findings for this section."""
        # Find research for this section
        section_research = self._find_research_for_section(mod_num, sec_num)

        if not section_research:
            return

        # Data slide
        data_points = section_research.get('data_for_section', [])
        if data_points:
            data_items = []
            sources = []

            for dp in data_points[:4]:  # Limit to 4 data points
                point = dp.get('data_point', '')
                source_id = dp.get('source', '')
                data_items.append(f"- {point}")

                # Track source for citation
                source = self._find_source(source_id)
                if source:
                    sources.append(source)

            if data_items:
                citations = self._format_citations(sources)

                slide = f"""---

### Data & Evidence

**Key Statistics:**

{self._format_lines(data_items)}

{citations}

<!--
SPEAKER NOTES:
- Discuss trends and implications
- Ask: "What surprises you about this data?"
-->"""
                self.slides.append(slide)

    def _add_section_summary(
        self,
        mod_num: int,
        sec_num: int,
        sec_title: str,
        objectives: List[str]
    ):
        """Generate section summary slide."""
        slide = f"""---

### Section {mod_num}.{sec_num} Summary

**Key Takeaways:**

{self._format_bullets(objectives[:3])}

**Coming Up Next:**

[Preview of next section]

<!--
SPEAKER NOTES:
- Reinforce main concepts
- Address any remaining questions
- Estimated time: 5 minutes
-->"""

        self.slides.append(slide)

    def _add_module_summary(self, mod_num: int, mod_title: str, sections: List[Dict]):
        """Generate module summary slides."""
        section_list = [
            f"**{s.get('section_title', 'Section')}** - Key learning"
            for s in sections
        ]

        slide = f"""---

## Module {mod_num} Summary

**What We Covered:**

{self._format_numbered_list(section_list)}

**Core Insights:**

- Major insight 1
- Major insight 2

<!--
SPEAKER NOTES:
- Review module objectives
- Connect to next module
- Estimated time: 10 minutes
-->"""

        self.slides.append(slide)

    def _add_course_conclusion(self):
        """Generate course conclusion slides."""
        modules = self.outline.get('modules', [])

        module_themes = [
            f"**{m.get('module_title', 'Module')}** - Key learning"
            for m in modules
        ]

        slide = f"""---

# Course Conclusion

**Journey Recap:**

{self._format_lines(module_themes)}

<!--
SPEAKER NOTES:
- Synthesize major themes
- Celebrate learning achievements
- Estimated time: 15 minutes
-->"""

        self.slides.append(slide)

        # Next steps
        next_slide = """---

## From Learning to Practice

**How to Apply This:**

- In your work: [Application area]
- In your projects: [Application area]
- In your growth: [Continuous learning]

**Next Steps:**

1. Review course materials
2. Complete final project
3. Continue learning

---

## Thank You!

**Questions?**

[Contact information]

**Stay Connected:**

[Community links]"""

        self.slides.append(next_slide)

    def _add_references(self):
        """Generate references slide."""
        sources = self.research.get('sources', [])

        if not sources:
            return

        slide = "---\n\n## References\n\n"

        for i, source in enumerate(sources[:20], 1):  # Limit to 20 sources
            title = source.get('title', 'Untitled')
            author = source.get('author', 'Unknown')
            url = source.get('url', '')
            date = source.get('publication_date', '')

            slide += f"{i}. {author}. \"{title}.\" {date}. {url}\n\n"

        self.slides.append(slide)

    # Helper methods

    def _find_outline_module(self, mod_num: int) -> Dict:
        """Find module in outline by number."""
        for module in self.outline.get('modules', []):
            if module.get('module_number') == mod_num:
                return module
        return {}

    def _find_research_for_section(self, mod_num: int, sec_num: int) -> Dict:
        """Find research findings for a specific section."""
        for finding in self.research.get('findings_by_section', []):
            if (finding.get('module') == mod_num and
                finding.get('section') == sec_num):
                return finding
        return {}

    def _find_source(self, source_id: str) -> Dict:
        """Find source by ID."""
        for source in self.research.get('sources', []):
            if source.get('source_id') == source_id:
                return source
        return {}

    def _format_bullets(self, items: List[str]) -> str:
        """Format list as markdown bullets."""
        if not items:
            return "- [To be determined]"
        return '\n'.join(f"- {item}" for item in items)

    def _format_numbered_list(self, items: List[str]) -> str:
        """Format list as numbered markdown list."""
        if not items:
            return "1. [To be determined]"
        return '\n'.join(f"{i}. {item}" for i, item in enumerate(items, 1))

    def _format_lines(self, items: List[str]) -> str:
        """Format list as lines with line breaks."""
        if not items:
            return "[To be determined]"
        return '\n\n'.join(items)

    def _format_citations(self, sources: List[Dict]) -> str:
        """Format source citations."""
        if not sources:
            return ""

        citations = []
        for source in sources:
            author = source.get('author', 'Unknown')
            title = source.get('title', 'Untitled')
            citations.append(f"*{author}, \"{title}\"*")

        return "\n\n**Sources:** " + "; ".join(citations)


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description='Generate presentation markdown from course materials'
    )
    parser.add_argument(
        '--outline',
        required=True,
        help='Path to course_outline.json'
    )
    parser.add_argument(
        '--brief',
        required=True,
        help='Path to content_brief.json'
    )
    parser.add_argument(
        '--research',
        required=True,
        help='Path to research_notes.json'
    )
    parser.add_argument(
        '--template',
        help='Path to presentation template (optional)'
    )
    parser.add_argument(
        '--output', '-o',
        default='final_presentation.md',
        help='Output markdown file (default: final_presentation.md)'
    )

    args = parser.parse_args()

    try:
        generator = PresentationGenerator(
            args.outline,
            args.brief,
            args.research,
            args.template
        )

        presentation = generator.generate()

        # Save output
        output_path = Path(args.output)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(presentation)

        print(f"\n✓ Success! Presentation saved to: {output_path}")
        print(f"  Presentation length: {len(presentation):,} characters")

        # Show preview
        lines = presentation.split('\n')
        print(f"  Total lines: {len(lines)}")
        print(f"  Slide breaks: {presentation.count('---')}")

    except Exception as e:
        print(f"\n✗ Error: {e}")
        import traceback
        traceback.print_exc()
        exit(1)


if __name__ == '__main__':
    main()
